config/routes.rb
Constrvct::Application.routes.draw do
  devise_for :admins, :controllers => {:sessions => 'admin_sessions'}

  resources :designs

  resources :textures

  resources :forms

  devise_for :users
  
  resources :users, :only => [:show]

  root :to => "designs#index"
  

end

app/models/design.rb
class Design < ActiveRecord::Base
  belongs_to :form
  belongs_to :texture
  belongs_to :user
  attr_accessible :form_id, :texture_id, :image_data, :title, :description, :preview
  

  has_attached_file :preview, :styles => { :thumb => "200x200>", :thumb => "100x100#" },
  :storage => :filesystem,
  :path => "public/designs/:id/:design_preview_:id.:extension",
  :url => "/designs/:id/:basename_:id.:extension"

  attr_accessor :image_data
  
end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController
  skip_before_filter :authenticate_user!, :only => [:index]
  before_filter :authenticate_admin!, :only => [:edit, :update]
  
  def constrvct
    #debugger
    @textures = Texture.find(:all, :limit => 21, :order=> 'created_at desc')
    @designs = Design.find(:all, :limit => 20, :order=> 'created_at desc')
  end
  
  # GET /designs
  # GET /designs.json
  def index
    #@designs = Design.all
    @designs = Design.find(:all, :limit => 20, :order=> 'created_at desc')
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @designs }
    end
  end

  # GET /designs/1
  # GET /designs/1.json
  def show
    @design = Design.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @design }
    end
  end

  # GET /designs/new
  # GET /designs/new.json
  def new
    @design = Design.new
    @textures = Texture.find(:all, :limit => 21, :order=> 'created_at desc')
    @designs = Design.find(:all, :limit => 20, :order=> 'created_at desc')
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @design }
    end
  end

  # GET /designs/1/edit
  def edit
    @design = Design.find(params[:id])
  end

  # POST /designs
  # POST /designs.json
  def create
    @design = Design.new(params[:design])
    @design.user = current_user
    
    temp_file_name = Rails.root.join('tmp', "preview#{@design.texture_id}.png")
    
    File.open(temp_file_name, 'wb') do |f|
      f.write Base64.decode64 @design.image_data.gsub(/^data:image\/(png|jpg)\;base64,/, "")
    end
    
    @design.preview_file_name = File.open(temp_file_name)

    respond_to do |format|
      if @design.save
        format.html { redirect_to @design, :notice => 'Design was successfully created.' }
        format.json { render :json => @design, :status => :created, :location => @design }
      else
        format.html { render :action => "new" }
        format.json { render :json => @design.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /designs/1
  # PUT /designs/1.json
  def update
    @design = Design.find(params[:id])

    respond_to do |format|
      if @design.update_attributes(params[:design])
        format.html { redirect_to @design, :notice => 'Design was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @design.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /designs/1
  # DELETE /designs/1.json
  def destroy
    @design = Design.find(params[:id])
    @design.destroy

    respond_to do |format|
      format.html { redirect_to designs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/designs_helper.rb
module DesignsHelper
end

app/views/designs/_form.html.erb
<%= form_for(@design) do |f| %>
  <% if @design.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@design.errors.count, "error") %> prohibited this design from being saved:</h2>

      <ul>
      <% @design.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :form_id %><br />
    <%= f.select :form_id, options_from_collection_for_select(Form.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :texture_id %><br />
    <%= f.select :texture_id, options_from_collection_for_select(Texture.all, :id, :name) %>
  </div>
  <div class="field">
  <%= f.label :title %><br />
  <%= f.text_field :title %>
  </div>
  <div class="field">
  <%= f.label :description %><br />
  <%= f.text_field :description %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/designs/constrvct.html.erb
<%= content_for :scripts do %>
  <script type="text/javascript" src='/assets/Three/Three.js'> </script>
  <script type="text/javascript" src="/assets/Three/OBJLoader.js"> </script>
  <script type="text/javascript" src="/assets/Three/Detector.js" > </script>
  <script type="text/javascript" src="/assets/Three/Stats.js" > </script>
  
  <script type="text/javascript">
    var selected_style_mesh;
    var selected_texture;
    
    function adopt_image(image, texture_id) {
      refresh(selected_style_mesh, image);
      $('#design-texture').val(texture_id);
      show_save_button();
    }
    function update_design() {
      refresh(selected_style_mesh, selected_texture);
      show_save_button();
    }
    
    function update_texture(file) {
      changeTexture(file);
      show_save_button();
    }
    function update_style() {
      changeModel(selected_style_mesh);
      show_save_button();
    }
    
    function show_save_button() {
      $('#save-button').show();
      $('#design-title').show();
    }
  
    $(function() {
      $("#texture_image").on('change', function() {
        if ($("#texture_image").val() != "") {
          //$("#upload-image-button").show();
          $('#new_texture span').html($("#texture_image").val());
          console.log('upload texture');
          $('#new_texture').submit();
        } else {
          $('#new_texture span').html('Use your own photo or image');
          //$("#upload-image-button").hide();
        }
      })
      
      $("#upload-button").click(function(){
        console.log('upload clicked');
        $("#texture_image").click();
      })
      
      $('.style img').click(function() {
        $('.style .selected').removeClass('selected');
        $(this).addClass('selected');
        $('#design-form').val($(this).data('form-id'));
        selected_style_mesh = $(this).data('mesh-file');
        update_style();
      });
      
      $('.texture-option').live('click', function() {
        $('.selected-texture').removeClass('selected-texture');
        $(this).addClass('selected-texture');
        selected_texture = $(this).data('img');
        $('#design-texture').val($(this).data('texture-id'));
        update_texture(selected_texture);
      });
      
      $('.recent-design').live('click', function() {
        $('.selected-design').removeClass('selected-design');
        $(this).parent().addClass('selected-design');
        selected_style_mesh = $(this).data('mesh-file');
        
        if ($(this).data('form-id') != $('#design-form').val()) {
          $('#design-form').val($(this).data('form-id'));
          adopt_image($(this).data('texture-file') , $(this).data('texture-id') );
        } else {
          update_texture($(this).data('texture-file') );
        }
      });
      
      $('#save-button').click(function() {
    
        var designrender = $('#GL')[0].toDataURL("image/png");
        $('#design-preview').val(designrender);
        var designdiv = document.createElement('div');
        designdiv.setAttribute('class', 'recent-design-group');
        var newdesign = document.createElement("img");  
        newdesign.src = designrender;
        newdesign.setAttribute('class','recent-design');
        newdesign.setAttribute('data-texture-id', $('#design-texture').val());
        newdesign.setAttribute('data-texture-file', selected_texture);
        newdesign.setAttribute('data-mesh-file', selected_style_mesh);
        newdesign.setAttribute('data-form-id', $('#design-form').val());
        designdiv.appendChild(newdesign);
        $("#my-closet").prepend(designdiv);
        
        $("#new_design").submit();
      });
      
      $('.style img').first().addClass('selected');
      
      $('#upload-image-button').click(function(){
        console.log('upload texture');
        $('#new_texture').submit();
      });
      
      selected_style_mesh = $('.style .selected').data('mesh-file');
      $('#design-form').val($('.style .selected').data('form-id'));
      
      selected_texture = $($('.texture-option')[0]).data('img');
      $('#design-texture').val($($('.texture-option')[0]).data('texture-id'));
      
      init3DBuild(selected_style_mesh, selected_texture );

      
    });
    
    function putDrawing() {
      var canvas = document.getElementById('drawing');
      loadCanvas(canvas); 
    }
   
  </script>
<% end %>

<script type="text/javascript">
console.log("hello");
</script>

  <div id="main-design">
    <div id="style-picker">
      <% Form.all.each do |style| %>
        <div class="style">
          <%= image_tag style.image.url(:thumb), :'data-mesh-file' => style.front_mesh.url, :'data-form-id' => style.id %>
        </div>
      <% end %>
    </div>
    
    <div id="render-container">
    </div>
    
    <%= form_for Design.new, :remote => true, :id => 'design-save' do |f| %>
      <%= f.hidden_field :texture_id, :id => 'design-texture' %>
      <%= f.hidden_field :form_id, :id => 'design-form' %>
      <%= f.hidden_field :image_data, :id => 'design-preview' %>
      <!--
      <%= f.submit 'Save this design!', :id => 'save-button', :style => 'display:none' %>
      -->
      <a class="button" id="save-button" style="display:none;"> SAVE YOUR LOOK </a>
      <div id="design-title" style="display:none;">
      <%= f.text_field :title, :placeholder => 'Title Your Look' %>
      </div>
    <% end %>
  </div>
  
  <div id="artwork">
    <h3>Add Artwork</h3>
    
    <%= form_for Texture.new, :remote => true, :id => 'texture-upload' do |f| %>
        <a class="button" id="upload-button"> Upload </a>
        <span>Use your own photo or image</span>
        <%= f.file_field :image, :style => 'display:none' %>
        <br />
        <a class="button" id="upload-image-button" style="display:none;"> Upload Image </a>
        <!--
        <%= f.submit 'Upload image', :id => 'upload-image-button', :style => 'display:none' %>
        -->
      <% end %>
      
    
    <div id="available-artwork">
      <div id="texture-picker">
      <% @textures.each do |texture| %>
          <%= image_tag texture.image.thumbnail, :'data-texture-id' => texture.id, :'data-img' => texture.image.square, :class=>"texture-option" %>
      <% end %>
      </div>
    </div>
  </div>

  <div id="available-designs">
    <h3>Newest Constrvcts</h3>
  <div id="recent-designs">
  <% @designs.each do |design| %>
    <div class="recent-design-group">
      <%= image_tag design.preview, :width => 100, :class =>'recent-design', :'data-mesh-file' => design.form.mesh, :'data-form-id' => design.form.id, :'data-texture-file' => design.texture.image.square, :'data-texture-id' => design.texture.id  %>
      <span>by <%= link_to design.user.username, design.user %></span>
    </div>  
  <% end %>
  </div>
  </div>

  
<script type="text/javascript" src='/assets/processingjs/processing-1.3.6.min.js'/>
<script type="application/processing" >
</script>
<canvas id="drawing" data-processing-sources="/assets/ptest.pde" style="display:none;" ></canvas>

<script>
function stopDrawing() {
  var processing = Processing.getInstanceById('drawing');
  processing.noLoop();
}
function startDrawing() {
  var processing = Processing.getInstanceById('drawing');
  processing.loop();
}
console.log("hello");

</script>

app/views/designs/edit.html.erb
<h1>Editing design</h1>

<%= render 'form' %>

<%= link_to 'Show', @design %> |
<%= link_to 'Back', designs_path %>

app/views/designs/index.html.erb
<h2>Newest Constrvcts</h2>


<div class="grid">
<% @designs.each do |design| %>
    <div class='grid-design-group'>
      <div class='design-unit'>
        <%= link_to design do %>
          <%= image_tag design.preview.url(:thumb200) %>
        <% end %>
        <div>
        <h5><%= design.title %></h5>
        <span> by <%= link_to design.user.username, design.user %></span>  
        </div>
      </div>
      
    <% if current_admin %>  
      <div class="admin-unit">
      

      <%= link_to 'Edit', edit_design_path(design) %>
      <%= link_to 'Destroy', design, :method => :delete, :data => { :confirm => 'Are you sure?' } %>
      </div>
      <% end %>
      
    </div>
<% end %>
</div>

<%= link_to 'New Constrvct', root_path %>

app/views/designs/new.html.erb
<%= content_for :scripts do %>
  <script type="text/javascript" src='/assets/Three/Three.js'> </script>
  <script type="text/javascript" src="/assets/Three/OBJLoader.js"> </script>
  <script type="text/javascript" src="/assets/Three/Detector.js" > </script>
  <script type="text/javascript" src="/assets/Three/Stats.js" > </script>
  <script type="text/javascript" src="/assets/3D-build.js" > </script>
  <script type="text/javascript">
    var front_mesh, back_mesh;
    var style_id, texture_id;
    var texture_file;
    
    function changeTexture(img){
    	console.log(img);
    	canvastexture = false;
    	texture = THREE.ImageUtils.loadTexture(img);

    	for (var a=0; a <holder.children.length; a++) {
    		for(var i = 0, l = holder.children[a].children.length; i < l; i++) {

    			holder.children[a].children[i].material.map = texture;
    			holder.children[a].children[i].doubleSided = true;
    		}
    	}
    }
    
    function changeModel(obj1, obj2) {
    	scene.remove(holder);
    	holder = new THREE.Object3D();

    	loadthis(obj1);
    	loadthis(obj2);
    	scene.add(holder);
    }
    
    function update_texture(file) {
      changeTexture(file);
      $('#design-texture').val(texture_id);
      show_save_button();
    }
    function update_style() {
      changeModel(front_mesh, back_mesh);
      $('#design-form').val(style_id);
      show_save_button();
    }
    
    function show_save_button() {
      $('#save-button').show();
      $('#design-title').show();
    }
  
    $(function() {
      $("#texture_image").on('change', function() {
        if ($("#texture_image").val() != "") {
          $('#new_texture span').html($("#texture_image").val());
          console.log('uploading texture');
          $('#new_texture').submit();
        } else {
          $('#new_texture span').html('Use your own photo or image');
        }
      })
      
      $("#upload-button").click(function(){
        console.log('upload clicked');
        $("#texture_image").click();
      })
      
      $('.style img').click(function() {
        $('.style .selected').removeClass('selected');
        $(this).addClass('selected');
        
        style_id = $(this).data('form-id');
        front_mesh = $(this).data('mesh-front');
        back_mesh = $(this).data('mesh-back');
        
        update_style();
      });
      
      $('.texture-option').live('click', function() {
        $('.selected-texture').removeClass('selected-texture');
        $(this).addClass('selected-texture');
        texture_file = $(this).data('img');
        
        texture_id=$(this).data('texture-id');
        update_texture(texture_file);
      });
      
      $('.recent-design').live('click', function() {
        $('.selected-design').removeClass('selected-design');
        $(this).parent().addClass('selected-design');
        front_mesh = $(this).data('mesh-front');
        back_mesh = $(this).data('mesh-back');
        texture_file = $(this).data('texture-file');
        
        if ($(this).data('form-id') != $('#design-form').val()) {
          style_id = $(this).data('form-id');
          update_texture(texture_file);
          update_style();
        } else {
          update_texture(texture_file );
        }
      });
      
      $('#save-button').click(function() {
    
        var designrender = $('#GL')[0].toDataURL("image/png");
        $('#design-preview').val(designrender);
        var designdiv = document.createElement('div');
        designdiv.setAttribute('class', 'recent-design-group');
        var newdesign = document.createElement("img");  
        newdesign.src = designrender;
        newdesign.setAttribute('class','recent-design');
        newdesign.setAttribute('data-texture-id', texture_id);
        newdesign.setAttribute('data-texture-file', texture_file);
        newdesign.setAttribute('data-mesh-front', front_mesh);
        newdesign.setAttribute('data-mesh-back', back_mesh);
        newdesign.setAttribute('data-form-id', style_id);
        designdiv.appendChild(newdesign);
        $("#my-closet").prepend(designdiv);
        
        $("#new_design").submit();
      });
      
      $('#upload-image-button').click(function(){
        console.log('uploading texture');
        $('#new_texture').submit();
      });
      
      $('.style img').first().addClass('selected');
      front_mesh = $('.style .selected').data('mesh-front');
      back_mesh = $('.style .selected').data('mesh-back');

      style_id = $('.style .selected').data('form-id');
      
      texture_file = $($('.texture-option')[0]).data('img');
      texture_id = $($('.texture-option')[0]).data('texture-id');
      
      init3DBuild(front_mesh, back_mesh, texture_file);
      console.log("init");
      loadthis(front_mesh);
      loadthis(back_mesh);
      $('#design-form').val(style_id);
      changeTexture(texture_file);
      
      
    });
    
    function putDrawing() {
      var canvas = document.getElementById('drawing');
      loadCanvas(canvas); 
    }
   
  </script>
<% end %>

  <div id="main-design">
    <div id="style-picker">
      <% Form.all.each do |style| %>
        <div class="style">
          <%= image_tag style.image.url(:thumb), :'data-mesh-front' => style.front_mesh.url, :'data-mesh-back' => style.back_mesh.url, :'data-form-id' => style.id %>
        </div>
      <% end %>
    </div>
    
    <div id="render-container">
    </div>
    
    <%= form_for Design.new, :remote => true, :id => 'design-save' do |f| %>
      <%= f.hidden_field :texture_id, :id => 'design-texture' %>
      <%= f.hidden_field :form_id, :id => 'design-form' %>
      <%= f.hidden_field :image_data, :id => 'design-preview' %>
      <!--
      <%= f.submit 'Save this design!', :id => 'save-button', :style => 'display:none' %>
      -->
      <a class="button" id="save-button" style="display:none;"> SAVE YOUR LOOK </a>
      <div id="design-title" style="display:none;">
      <%= f.text_field :title, :placeholder => 'Title Your Look' %>
      </div>
    <% end %>
  </div>
  
  <div id="artwork">
    <h3>Add Artwork</h3>
    
    <%= form_for Texture.new, :remote => true, :id => 'texture-upload' do |f| %>
        <a class="button" id="upload-button"> Upload </a>
        <span>Use your own photo or image</span>
        <%= f.file_field :image, :style => 'display:none' %>
        <br />
        <a class="button" id="upload-image-button" style="display:none;"> Upload Image </a>
        <!--
        <%= f.submit 'Upload image', :id => 'upload-image-button', :style => 'display:none' %>
        -->
      <% end %>
      
    
    <div id="available-artwork">
      <div id="texture-picker">
      <% @textures.each do |texture| %>
          <%= image_tag texture.image.url(:thumb), :'data-texture-id' => texture.id, :'data-img' => texture.image.url(:v512), :class=>"texture-option" %>
      <% end %>
      </div>
    </div>
  </div>
<!--
  <div id="available-designs">
    <h3>Newest Constrvcts</h3>
  <div id="recent-designs">
  <% @designs.each do |design| %>
    <div class="recent-design-group">
     <%= image_tag design.preview.url(:thumb), :width => 100, :class =>'recent-design', :'data-mesh-front' => design.form.front_mesh.url, :'data-mesh-back' => design.form.back_mesh.url, :'data-form-id' => design.form.id, :'data-texture-file' => design.texture.image.url(:v512), :'data-texture-id' => design.texture.id  %>
      <span>by <%= link_to design.user.username, design.user %></span>
    </div>  
  <% end %>
  </div>
  </div>
--> 
  
<script type="text/javascript" src='/assets/processingjs/processing-1.3.6.min.js'/>
<script type="application/processing" >
</script>
<canvas id="drawing" data-processing-sources="/assets/ptest.pde" style="display:none;" ></canvas>

<script>
function stopDrawing() {
  var processing = Processing.getInstanceById('drawing');
  processing.noLoop();
}
function startDrawing() {
  var processing = Processing.getInstanceById('drawing');
  processing.loop();
}

</script>

app/views/designs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="grid">
<div id="render-container">
  
</div>

<div class="design-info">
  <h3 class="design-title"><%= @design.title %></h3>
  <h4><span class="grey">constrvcted by </span><%= link_to @design.user.username, user_path(@design.user) %></h4>
  <p>
   <%= @design.description %> 
  </p>  
  <p>
    <%= image_tag @design.texture.image.(:thumb), :width => 100 %>
    <%= image_tag @design.form.image.url(:thumb), :width => 100 %>
  </p>
  <h4><span class="grey">artwork by </span> <%= link_to @design.texture.user.username, user_path(@design.texture.user) %></h4>
  <h4><span class="grey">style: </span> <%= @design.form.name %></h4>
</div>

<% if current_admin %>  
<%= link_to 'Edit', edit_design_path(@design) %> |
<%= link_to 'Back', designs_path %>
<% end %>
</div>
<div class="grid">
  <div class="width50">
  <h3 class="underline">also by <%= link_to @design.user.username, user_path(@design.user) %></h3>
  <% @design.user.designs.each do |userdesign| %>
    <% if userdesign.id != @design.id %>
      <div class='recent-design-group outline'>
          <%= link_to userdesign do %>
            <%= image_tag userdesign.preview.url(:thumb) %>
          <% end %>
      </div>
    <% end %>
  <% end %>
  </div>
</div>

<%= content_for :scripts do %>
  <script type="text/javascript" src="/assets/Three/Three.js" />
  <script type="text/javascript" src="/assets/Three/OBJLoader.js" />
  <script type="text/javascript" src="/assets/Three/Detector.js" />
  <script type="text/javascript" src="/assets/Three/Stats.js" />
  <script type="text/javascript" src="/assets/3D-build.js" > </script>
  
  <script type="text/javascript">
    $(function() {
      init3DBuild('<%= @design.form.front_mesh.url %>','<%= @design.form.back_mesh.url %>', '<%= @design.texture.image.square %>');
    });
  </script>
<% end %>