config/routes.rb
Constrvct::Application.routes.draw do
  devise_for :admins, :controllers => {:sessions => 'admin_sessions'}

  resources :designs

  resources :textures

  resources :forms

  devise_for :users
  
  resources :users, :only => [:show]

  root :to => "designs#index"
  

end

app/models/texture.rb
class Texture < ActiveRecord::Base
  has_many :designs
  belongs_to :user
  
  attr_accessible :image, :name, :description
  
  has_attached_file :image, :styles => { :v512 =>"512x512#", :medium => "600x600>", :thumb => "100x100#" },
  :storage => :filesystem,
  :path => "public/textures/:id/:basename_:style.:extension",
  :url => "/textures/:id/:basename_:style.:extension"
end

app/controllers/textures_controller.rb
class TexturesController < ApplicationController
  skip_before_filter :authenticate_user!
  before_filter :authenticate_admin!, :only => [:index, :show, :edit, :update]
  # GET /textures
  # GET /textures.json
  def index
    @textures = Texture.find(:all, :limit => 20, :order=> 'created_at desc')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @textures }
    end
  end

  # GET /textures/1
  # GET /textures/1.json
  def show
    @texture = Texture.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @texture }
    end
  end

  # GET /textures/new
  # GET /textures/new.json
  def new
    @texture = Texture.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @texture }
    end
  end

  # GET /textures/1/edit
  def edit
    @texture = Texture.find(params[:id])
  end

  # POST /textures
  # POST /textures.json
  def create
    @texture = Texture.new(params[:texture])
    @texture.user = current_user
    
    respond_to do |format|
      if @texture.save
        format.js
        format.html { redirect_to @texture, :notice => 'Texture was successfully created.' }
        format.json { render :json => @texture, :status => :created, :location => @texture }
      else
        format.html { render :action => "new" }
        format.json { render :json => @texture.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /textures/1
  # PUT /textures/1.json
  def update
    @texture = Texture.find(params[:id])

    respond_to do |format|
      if @texture.update_attributes(params[:texture])
        format.html { redirect_to @texture, :notice => 'Texture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @texture.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /textures/1
  # DELETE /textures/1.json
  def destroy
    @texture = Texture.find(params[:id])
    @texture.destroy

    respond_to do |format|
      format.html { redirect_to textures_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/textures_helper.rb
module TexturesHelper
end

app/views/textures/_form.html.erb
<%= form_for @texture, :html => { :multipart => true } do |f| %>
  <% if @texture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@texture.errors.count, "error") %> prohibited this texture from being saved:</h2>

      <ul>
      <% @texture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/textures/create.js.erb
$('.selected-texture').removeClass('selected-texture');
$("#texture-picker").prepend('<%= escape_javascript image_tag(@texture.image.url(:v512), :'data-texture-id' => @texture.id, :'data-img' => @texture.image.url(:v512), :width => 100, :class=>"texture-option selected-texture") %>');

$('#design-texture').val(<%= @texture.id %>);
texture_file = '<%= @texture.image.url(:v512) %>';
update_texture(texture_file);

app/views/textures/edit.html.erb
<h1>Editing texture</h1>

<%= render 'form' %>

<%= link_to 'Show', @texture %> |
<%= link_to 'Back', textures_path %>

app/views/textures/index.html.erb
<h1>All textures</h1>

<table>


<% @textures.each do |texture| %>
  <tr>
    <td><%= link_to texture.name, texture %></td>
    <td><%= image_tag texture.image.url(:thumb) %></td>
    <td><%= link_to 'Edit', edit_texture_path(texture) %></td>
    <td><%= link_to 'Destroy', texture, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Texture', new_texture_path %>

app/views/textures/new.html.erb
<h1>New texture</h1>

<%= render 'form' %>

<%= link_to 'Back', textures_path %>

app/views/textures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= @texture.name %></b>
</p>

<p>
  <%= image_tag @texture.image.url(:v512) %>
</p>


<%= link_to 'Edit', edit_texture_path(@texture) %> |
<%= link_to 'Back', textures_path %>