config/routes.rb
Constrvct::Application.routes.draw do
  devise_for :admins, :controllers => {:sessions => 'admin_sessions'}

  resources :designs

  resources :textures

  resources :forms

  devise_for :users
  
  resources :users, :only => [:show]

  root :to => "designs#index"
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CONSTRVCT</title>
  <link href='http://fonts.googleapis.com/css?family=Quicksand|Tenor+Sans' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  
  <%= javascript_include_tag "application" %>
  
  <%= csrf_meta_tags %>
  <%= yield :scripts %>
</head>
<body>
	

  <% if current_admin %>
  <div id="admin-toolbar">
    Welcome Admin.
    <%= link_to 'log out', destroy_admin_session_path, :method => :delete %>
    <%= link_to 'Forms', forms_path %>
    <%= link_to 'Textures', textures_path %>
    </div>
  <% end %>
  
  <div id="top">
  <a href="/"><h1 id="logotype">CONSTRVCT</h1></a>
  </div>
  
  <nav id="main-nav">
    <%= link_to 'Constrvct Your Look', new_design_path %>
    <div id="my-closet"></div>
    
    <% if current_user %>
      <%= link_to 'My Closet', current_user %>
    <% end %>
     
    <%= link_to 'All Constrvcts', designs_path %>
    
    <nav id="registration">
      <% if current_user %>
        <%= link_to 'Log Out', destroy_user_session_path, :method=>:delete %>
      <% else %>
        <%= link_to 'Sign Up', new_user_registration_path %>
        <%= link_to 'Sign In', new_user_session_path %>    
      <% end %>
    </nav>
    
  </nav>
  
  <!--
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  -->
<div id="main-container">  
<%= yield %>
</div>
</body>
</html>